# Generated by Django 3.0.3 on 2021-02-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.EmailField(default='raghav.shetty100@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='message',
            field=models.CharField(default='hi', max_length=26, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='raghavendra', max_length=26, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default='91'),
        ),
    ]
